name: Example Workflow

on: push  # Triggers the workflow when a push event occurs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a sample command
        run: echo "This workflow runs on push events"
